# Generated by Django 2.0.7 on 2019-09-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placcount',
            name='locations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
