# Generated by Django 2.0.7 on 2019-09-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0002_placcount_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placcount',
            old_name='locations',
            new_name='location',
        ),
    ]
