# Generated by Django 2.0.7 on 2019-08-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0002_auto_20190829_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='placcount',
            name='pltype',
            field=models.CharField(choices=[('REV', 'Revenue'), ('COG', 'Cost of Goods'), ('EXP', 'Expense')], default='EXP', max_length=3),
        ),
    ]
