# Generated by Django 2.0.7 on 2019-09-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='newCoDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
